flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField

class PostForm(FlaskForm):
	title = StringField('Title')
	content = TextAreaField('Content')
	submit = SubmitField('Post')

	def validate_title(self, title):
		if title.data == '':
			raise ValidationError('the title field is empty')

	def validate_content(self, content):
		if content.data == '':
			raise ValidationError('your post must have some content')
	

flask_blog/main/routes.py
from flask import render_template, request, Blueprint
from flask_blog.models import Post

main = Blueprint('main', __name__)



@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)

# This is an about page


@main.route('/about')
def about():
    return render_template('about.html', title='About')

flask_blog/posts/routes.py
from flask import (Blueprint, render_template, redirect, flash, 
                   request, url_for, abort)
from flask_login import current_user, login_required
from flask_blog import db
from flask_blog.models import Post
from flask_blog.posts.forms import PostForm

posts = Blueprint('posts', __name__)



# the post page

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/new', methods=['GET', 'POST'])
def create_post():
    posts = Post.query.all()
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, 
            author=current_user)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')

 
@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated successfully', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='update_post',
     form=form, legend='update post')

@posts.route('/post/<int:post_id>/delete', methods=['GET', 'POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("your post has been deleted successfully", 'success')
    return redirect(url_for('main.home'))

flask_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from flask_blog.users.forms import(RegistrationForm, LoginForm, UpdateAccountForm, 
                                   RequestResetForm, ResetPasswordForm)
from flask_blog.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)



@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, 
            email=form.email.data, 
            password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Acoount created for {form.username.data}!, you can login now', 
            'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', title='register', form=form)

# login page


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            next_page = request.args.get('next')
            login_user(user, remember=form.remember.data)
            print(next_page)
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('login unsuccessful pls check your email and password')
    return render_template('login.html', title='login', form=form)

# logout function


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


# user account page
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return (posts, user)

@users.route('/account/<string:username>', methods=['GET', 'POST'])
@login_required
def account(username):
    posts, user = user_posts(username)
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        db.session.commit()
        flash('your account has been updated!', 'success')
        return redirect(url_for('users.account', 
            username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static',
     filename='profile_pics/' + user.image_file)
    return render_template('account.html', title='account',
         image_file=image_file, form=form, posts=posts, user=user)



@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instruction to reset the password', 'warning')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password',
         form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if not user:
        flask('Token is invlaid or expired', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been reset successfully', 
            'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='reset_password',
         form=form)

flask_blog/templates/about.html
{% extends 'layout.html' %}
{% block content %}
	<h1>About Page</h1>
{% endblock content %}

flask_blog/templates/account.html
{% extends 'layout.html' %}
{% block content %}
	<div class="content-section">
		<div class="media">
			<img class="rounded-circle account-img" src="{{ image_file }}">
			<div class="media-body">
				<h2 class="account-heading"><em style="color: goldenrod;">{{ user.username }}</em></h2>
				<p class="text-secondary">{{ user.email }}</p>
				<p><em>i'm cool</em></p>
			</div>
		</div>

<!-- Account update Form collapse -->
		{% if user.username == current_user.username %}
		  	<div class="card">
		    	<div class="card-header">
	        		<button class="btn btn-block btn-primary" type="button" data-toggle="collapse" data-target="#updateformcollapse" aria-expanded="true" aria-controls="updateformcollapse">Account Info
	        		</button>
		    	</div>
				
				<div class="collapse show card-body" id='updateformcollapse'>
				    <form method="POST" action="" enctype="multipart/form-data">
				        {{ form.hidden_tag() }}
				        <fieldset class="form-group">
				            <div class="form-group">
				                {{ form.username.label(class="form-control-label") }}
				                {% if form.username.errors %}
				                    {{ form.username(class="form-control form-control-lg is-invalid") }}
				                    <div class="invalid-feedback">
				                        {% for error in form.username.errors %}
				                            <span>{{ error }}</span>
				                        {% endfor %}
				                    </div>
				                {% else %}
				                    {{ form.username(class="form-control form-control-lg") }}
				                {% endif %}
				            </div>
				            <div class="form-group">
				                {{ form.email.label(class="form-control-label") }}
				                {% if form.email.errors %}
				                    {{ form.email(class="form-control form-control-lg is-invalid") }}
				                    <div class="invalid-feedback">
				                        {% for error in form.email.errors %}
				                            <span>{{ error }}</span>
				                        {% endfor %}
				                    </div>
				                {% else %}
				                    {{ form.email(class="form-control form-control-lg") }}
				                {% endif %}
				            </div>
				            <div class="form-group">
				            	{{ form.picture.label() }}
				            	{{ form.picture(class='form_control_file') }}
				            	{% if form.picture.errors %}
				            		{% for error in form.picture.errors %}
				            			<span class="text-danger">{{ error }}</ span><br>
				            		{% endfor %}
				            	{% endif %}
				        </fieldset>
				        <div class="form-group">
				            {{ form.submit(class="btn btn-outline-info") }}
				        </div>
				    </form>
				</div>
			</div>
		{% endif %}

	</div>

<!-- The user posts -->

	<h2 class="mb-4"><em><pre>Posts : {{ posts.total }}</pre></em></h2>
	{% for post in posts.items %}
		<article class="media content-section">
			<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/'+ post.author.image_file) }}">
			<div class="media-body">
				<div class="article-metadata">
					<a href="#" class="mr-2">{{post.author.username}}</a>
					<small class='text-muted'>{{post.date_posted.strftime('%Y-%m-%d')}}</small>
				</div>			
				<h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{post.title}}</a></h2>
				<p class="article-content">{{post.content}}</p>
			</div>
		</article>
	{% endfor %}
	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
		{% if page_num %}
			{% if posts.page == page_num %}
				<a class="btn btn-info mb-4" href="{{url_for('users.account', username=user.username, page=page_num)}}">{{ page_num }}</a>
			{% else %}
				<a class="btn btn-outline-info mb-4" href="{{url_for('users.account',username=user.username,  page=page_num)}}">{{ page_num }}</a>
			{% endif %}
		{% else %}
			...
		{% endif %}
	{% endfor %} 
{% endblock content %}

flask_blog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

	{% if title %}
		<title>flask blog-{{title}}</title>
	{% else %}
		<title>flask blog</title>
	{% endif %}
</head>
<body>
	<header class='site-header'>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		  <a class="navbar-brand" href="#">Flask-blog</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">

		      <li class="nav-item active">
		        <a class="nav-link" href="{{ url_for('main.home') }}">
		        	<svg xmlns="http://www.w3.org/2000/svg" width="30" height="35" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
					  <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
					  <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
					</svg>
		        	<span class="sr-only">(current)</span></a>
		      </li>

		      <li class="nav-item">
		        <a class="nav-link" href="{{ url_for('main.about') }}">
		        	<svg xmlns="http://www.w3.org/2000/svg" width="30" height="35" fill="currentColor" class="bi bi-info-lg" viewBox="0 0 16 16">
					  <path d="m10.277 5.433-4.031.505-.145.67.794.145c.516.123.619.309.505.824L6.101 13.68c-.34 1.578.186 2.32 1.423 2.32.959 0 2.072-.443 2.577-1.052l.155-.732c-.35.31-.866.434-1.206.434-.485 0-.66-.34-.536-.939l1.763-8.278zm.122-3.673a1.76 1.76 0 1 1-3.52 0 1.76 1.76 0 0 1 3.52 0z"/>
					</svg>
		        </a>
		      </li>

		      <li class="nav-item dropdown">
		        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="35" fill="currentColor" class="bi bi-diagram-3" viewBox="0 0 16 16">
					  <path fill-rule="evenodd" d="M6 3.5A1.5 1.5 0 0 1 7.5 2h1A1.5 1.5 0 0 1 10 3.5v1A1.5 1.5 0 0 1 8.5 6v1H14a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-1 0V8h-5v.5a.5.5 0 0 1-1 0V8h-5v.5a.5.5 0 0 1-1 0v-1A.5.5 0 0 1 2 7h5.5V6A1.5 1.5 0 0 1 6 4.5v-1zM8.5 5a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1zM0 11.5A1.5 1.5 0 0 1 1.5 10h1A1.5 1.5 0 0 1 4 11.5v1A1.5 1.5 0 0 1 2.5 14h-1A1.5 1.5 0 0 1 0 12.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm4.5.5A1.5 1.5 0 0 1 7.5 10h1a1.5 1.5 0 0 1 1.5 1.5v1A1.5 1.5 0 0 1 8.5 14h-1A1.5 1.5 0 0 1 6 12.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm4.5.5a1.5 1.5 0 0 1 1.5-1.5h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"/>
					</svg>
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
		          <a class="dropdown-item" href="#">Action</a>
		          <a class="dropdown-item" href="#">Another action</a>
		          <div class="dropdown-divider"></div>
		          <a class="dropdown-item" href="#">Something else here</a>
		        </div>
		      </li>

		      <li class="nav-item">
		        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
		      </li>
		    </ul>
		    {% if current_user.is_authenticated %}
				
				<a class="nav-link my-2 my-sm-0" href="{{url_for('posts.create_post')}}">
					<svg xmlns="http://www.w3.org/2000/svg" width="30" height="35" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
					  <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
					</svg>
				</a>

				<a class="nav-link my-2 my-sm-0" href="{{url_for('users.account', username=current_user.username)}}">
					<svg xmlns="http://www.w3.org/2000/svg" width="30" height="35" fill="currentColor" class="bi bi-person-bounding-box" viewBox="0 0 16 16">
					  <path d="M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1h-3zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5zM.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0 14.5v-3a.5.5 0 0 1 .5-.5zm15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5z"/>
					  <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
					</svg>
				</a>

		        <a class="nav-link mr-sm-2" href="{{url_for('users.logout')}}">
			      	<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
						<path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
						<path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
					</svg>
		      	</a>
		      
		    {% else %}
		    	<a class="nav-link my-2 my-sm-0" href="{{url_for('users.login')}}">
		    		<svg xmlns="http://www.w3.org/2000/svg" width="30" height="35" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
					  <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
					  <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
					</svg>
		    	</a>

			    <a class="nav-link mr-sm-2" href="{{url_for('users.register')}}">
			    	<svg xmlns="http://www.w3.org/2000/svg" width="30" height="35" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
					  <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
					  <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
					</svg>
			    	
			    </a>
			{% endif %}
		  </div>
		</nav>
	</header>
	</div>
	<main role='main' class='container'>
		<div class="row">
			<div class='col-md-8'>
				{% with messages = get_flashed_messages(with_categories=True) %}
					{% if messages %}
						{% for category, message in messages %}
							<div class="alert alert-dismissible alert-{{category}} fade show">
								{{message}}
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    								<span aria-hidden="true">&times;</span>
  								</button>
							</div>
						{% endfor %}
					{% endif %}
				{% endwith %}
				{% block content %}{% endblock %}				
			</div>
			<div class='col-md-4'>
				<div class="content-section">
					<h3 style="padding-left: 40px;"><em>Side Bar</em></h3>
					<ul>
						<li class="media content-section">Latest</li>
						<li class="media content-section">Announcement</li>
						<li class="media content-section" style="margin-bottom: 40px;">Events</li>
					</ul>
				</div>				
			</div>
		</div>
	</main> 

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
</body>
</html>

flask_blog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Sign In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class='form-check-input') }}
                    {{ form.remember.label(class='form-check-label')}}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">forgot password?</a>
            </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don't Have an Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up</a>
        </small>
    </div>
{% endblock content %}

flask_blog/templates/post.html
{% extends 'layout.html' %}
{% block content %}

<!-- The post page -->

	<article class="media content-section">
		<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/'+ post.author.image_file) }}">
		<div class="media-body">
			<div class="article-metadata">
				<a href="#" class="mr-2">{{post.author.username}}</a>
				<small class='text-muted'>{{post.date_posted.strftime('%Y-%m-%d')}}</small>
			</div>
			{% if post.author == current_user %}
				<div>
					<a class="btn btn-secondary btn-sm m-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">update</a>
					<a type="button" class="btn btn-danger" href="#" data-target='#deleteModal' data-toggle='modal'>delete</a>
				</div>	
			{% endif %}
			<h2 class="article-title">{{post.title}}</h2>
			<p class="article-content">{{post.content}}</p>
		</div>
	</article>
	<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
	  	<div class="modal-dialog">
	    	<div class="modal-content">
	      	<div class="modal-header">
	        	<h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
	        	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          	<span aria-hidden="true">&times;</span>
	        	</button>
	      	</div>
	      	<div class="modal-footer">
		        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		       <form method="POST" action="{{ url_for('posts.delete_post', post_id=post.id) }}">
		       	<input type="submit" class="btn btn-danger" value="Delete">
		       </form>
	      	</div>
	   	</div>
	  </div>
	</div>

{% endblock content %}